name: football_field_find
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  l: ^4.0.2
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  device_preview: ^1.2.0
  go_router: ^14.2.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
          weight: 100
          style: italic